# Notes
# - cannot run on Windows, as we use shell scripts
# - removed macos from most jobs to speed up the process

name: "Validate"

on: [pull_request, push]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'oracle'
  HELIDON_PIPELINES: 'true'
  MAVEN_HTTP_ARGS: '-Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    environment: pipeline
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven build
        env:
          HELIDON_OCI_IT_REGION: ${{ secrets.HELIDON_OCI_IT_REGION }}
          HELIDON_OCI_IT_TENANCY: ${{ secrets.HELIDON_OCI_IT_TENANCY }}
          HELIDON_OCI_IT_USER: ${{ secrets.HELIDON_OCI_IT_USER }}
          HELIDON_OCI_IT_FINGERPRINT: ${{ secrets.HELIDON_OCI_IT_FINGERPRINT }}
          HELIDON_OCI_IT_KEY: ${{ secrets.HELIDON_OCI_IT_KEY }}
        run: |
          mvn -B -e "-Dmaven.test.skip=true" $MAVEN_HTTP_ARGS -DskipTests -Ppipeline install 
          cd integrations/oci/oci
          mvn -B verify
